{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-microservices.databaseName" . }}
  labels:
    {{- include "lab-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
{{- end }}

