apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab-microservices.secretName" . }}
  labels:
    {{- include "lab-microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%d/%s" .Values.database.auth.username .Values.database.auth.password (include "lab-microservices.databaseName" .) (int .Values.database.service.port) .Values.database.auth.database | quote }}

