{{- if .Values.security.serviceAccounts.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lab-microservices.frontendServiceAccountName" . }}
  labels:
    {{- include "lab-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: {{ .Values.security.serviceAccounts.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lab-microservices.backendServiceAccountName" . }}
  labels:
    {{- include "lab-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
automountServiceAccountToken: {{ .Values.security.serviceAccounts.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lab-microservices.databaseServiceAccountName" . }}
  labels:
    {{- include "lab-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
automountServiceAccountToken: {{ .Values.security.serviceAccounts.automountServiceAccountToken }}
{{- end }}
