grafana:
  enabled: true
  adminUser: admin
  adminPassword: lab09-admin
  service:
    type: ClusterIP
  sidecar:
    datasources:
      enabled: true

loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: false
  config:
    auth_enabled: false
    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h

promtail:
  enabled: true
  config:
    clients:
      - url: http://observability-loki:3100/loki/api/v1/push
    snippets:
      extraRelabelConfigs:
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container

prometheus:
  enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false

filebeat:
  enabled: false

logstash:
  enabled: false
